#!/bin/bash

AR_ROOT=$( cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)

# catkin workspace alias
alias AR_source="source ${AR_ROOT}/ar_environment.sh"
alias AR_clean="cd ${AR_ROOT}/build && make clean"
alias AR_build="cd ${AR_ROOT} && rm -f -r build && mkdir build && cd build && cmake .."
alias AR_make="cd ${AR_ROOT}/build && make"
alias AR_cd="cd ${AR_ROOT}"
